/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Section = IDL.Variant({
  'amd' : IDL.Null,
  'smc' : IDL.Null,
  'gainzalgo' : IDL.Null,
  'htgold' : IDL.Null,
});
export const Direction = IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null });
export const Signal = IDL.Record({
  'id' : IDL.Nat,
  'direction' : Direction,
  'pair' : IDL.Text,
  'section' : Section,
  'entry' : IDL.Int,
  'target' : IDL.Int,
  'timestamp' : IDL.Int,
  'stoploss' : IDL.Int,
  'confidence' : IDL.Int,
});

export const idlService = IDL.Service({
  'createSignal' : IDL.Func(
      [Section, IDL.Text, Direction, IDL.Int, IDL.Int, IDL.Int, IDL.Int],
      [IDL.Nat],
      [],
    ),
  'getAllSignals' : IDL.Func([], [IDL.Vec(Signal)], ['query']),
  'readSignal' : IDL.Func([IDL.Nat], [IDL.Opt(Signal)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Section = IDL.Variant({
    'amd' : IDL.Null,
    'smc' : IDL.Null,
    'gainzalgo' : IDL.Null,
    'htgold' : IDL.Null,
  });
  const Direction = IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null });
  const Signal = IDL.Record({
    'id' : IDL.Nat,
    'direction' : Direction,
    'pair' : IDL.Text,
    'section' : Section,
    'entry' : IDL.Int,
    'target' : IDL.Int,
    'timestamp' : IDL.Int,
    'stoploss' : IDL.Int,
    'confidence' : IDL.Int,
  });
  
  return IDL.Service({
    'createSignal' : IDL.Func(
        [Section, IDL.Text, Direction, IDL.Int, IDL.Int, IDL.Int, IDL.Int],
        [IDL.Nat],
        [],
      ),
    'getAllSignals' : IDL.Func([], [IDL.Vec(Signal)], ['query']),
    'readSignal' : IDL.Func([IDL.Nat], [IDL.Opt(Signal)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };