/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Signal {
    id: bigint;
    direction: Direction;
    pair: string;
    section: Section;
    entry: bigint;
    target: bigint;
    timestamp: bigint;
    stoploss: bigint;
    confidence: bigint;
}
export enum Direction {
    buy = "buy",
    sell = "sell"
}
export enum Section {
    amd = "amd",
    smc = "smc",
    gainzalgo = "gainzalgo",
    htgold = "htgold"
}
export interface backendInterface {
    createSignal(section: Section, pair: string, direction: Direction, entry: bigint, target: bigint, stoploss: bigint, confidence: bigint): Promise<bigint>;
    getAllSignals(): Promise<Array<Signal>>;
    readSignal(id: bigint): Promise<Signal | null>;
}
import type { Direction as _Direction, Section as _Section, Signal as _Signal } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createSignal(arg0: Section, arg1: string, arg2: Direction, arg3: bigint, arg4: bigint, arg5: bigint, arg6: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createSignal(to_candid_Section_n1(this._uploadFile, this._downloadFile, arg0), arg1, to_candid_Direction_n3(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSignal(to_candid_Section_n1(this._uploadFile, this._downloadFile, arg0), arg1, to_candid_Direction_n3(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async getAllSignals(): Promise<Array<Signal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSignals();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSignals();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async readSignal(arg0: bigint): Promise<Signal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.readSignal(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.readSignal(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Direction_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Direction): Direction {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Section_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Section): Section {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Signal_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Signal): Signal {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Signal]): Signal | null {
    return value.length === 0 ? null : from_candid_Signal_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    direction: _Direction;
    pair: string;
    section: _Section;
    entry: bigint;
    target: bigint;
    timestamp: bigint;
    stoploss: bigint;
    confidence: bigint;
}): {
    id: bigint;
    direction: Direction;
    pair: string;
    section: Section;
    entry: bigint;
    target: bigint;
    timestamp: bigint;
    stoploss: bigint;
    confidence: bigint;
} {
    return {
        id: value.id,
        direction: from_candid_Direction_n8(_uploadFile, _downloadFile, value.direction),
        pair: value.pair,
        section: from_candid_Section_n10(_uploadFile, _downloadFile, value.section),
        entry: value.entry,
        target: value.target,
        timestamp: value.timestamp,
        stoploss: value.stoploss,
        confidence: value.confidence
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    amd: null;
} | {
    smc: null;
} | {
    gainzalgo: null;
} | {
    htgold: null;
}): Section {
    return "amd" in value ? Section.amd : "smc" in value ? Section.smc : "gainzalgo" in value ? Section.gainzalgo : "htgold" in value ? Section.htgold : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    buy: null;
} | {
    sell: null;
}): Direction {
    return "buy" in value ? Direction.buy : "sell" in value ? Direction.sell : value;
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Signal>): Array<Signal> {
    return value.map((x)=>from_candid_Signal_n6(_uploadFile, _downloadFile, x));
}
function to_candid_Direction_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Direction): _Direction {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Section_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Section): _Section {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Section): {
    amd: null;
} | {
    smc: null;
} | {
    gainzalgo: null;
} | {
    htgold: null;
} {
    return value == Section.amd ? {
        amd: null
    } : value == Section.smc ? {
        smc: null
    } : value == Section.gainzalgo ? {
        gainzalgo: null
    } : value == Section.htgold ? {
        htgold: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Direction): {
    buy: null;
} | {
    sell: null;
} {
    return value == Direction.buy ? {
        buy: null
    } : value == Direction.sell ? {
        sell: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
